/**
 * @param {number[]} nums
 * @return {number[]}
 */
var smallerNumbersThanCurrent = function (nums) {
  let Map = {};
  let arr = [];
  nums.forEach((num, index) => {
    for (let i = 0; i < nums.length; i++) {
      if (nums[i] < num) {
        if (Map[index]) Map[index] += 1;
        else Map[index] = 1;
      }
    }
  });
  nums.forEach((num, index) => {
    if (!Map[index]) Map[index] = 0;
    arr.push(Map[index]);
  });
  return arr;
};
let nums = [8, 1, 2, 2, 3]
// console.log('smallerNumbersThanCurrent', smallerNumbersThanCurrent(nums));
/**
 * @param {string[]} votes
 * @return {string}
 */

var rankTeams = function (votes) {
  if (votes.length === 1) return votes[0];
  let MapIndex = []; //权重
  let Map = {
  }
  votes.forEach((v,i) => {
    for(let j = 0, len = v.length; j < len;j++) {
      if(!Map[j]) Map[j] = [v[j]];
      Map[j].push(v[j]);
    }
  });
  function sortMost (arr,i) {
    let arrMap = {};
    arr.forEach( ar=> {
      if(arrMap[ar]) arrMap[ar]++;
      else arrMap[ar] = 1;
    });
    let keys = Object.keys(arrMap);
    let sortArrMap = keys.sort((a,b) => {
      return arrMap[a] > arrMap[b] ? -1 : 1;
    });
    return sortArrMap[i];
  }
  let mapKeys = Object.keys(Map);
  let most = [];
  mapKeys.forEach((key,index) => {
    most.push(sortMost(Map[key],0));
  })
  // let sortRank = keys.sort((a,b) =>{
  //   if(Map[a] > Map[b]) return -1;
  //   if(Map[a] === Map[b])  {
  //     return a < b ?  -1 : 1;
  //   }
  //   else return 1;
  // });
  return most.join("");
};
let votes = ["PGAOFXIKYJVSLTUHCZQRE",
"LSIAPTHYCGURKEZXJOFQV",
"UGSARZICOXYPHTQFJKVEL",
"XIAOKSVGRJCHQZUETLYPF",
"OHRXPGEVUYCSKZILQATFJ",
"UHFSCZVKIELGOQJYRXPAT",
"QECXVZKJTLIYHUFRGOSAP",
"RJGAZIKPEVUSTOXFQYCHL",
"XRFGPAQSJOETHVCZIKLUY",
"ZCTQOVRFKXJGEALSHIYUP",
"QGTEHXCJRIPSUZALOYFVK","GIHXVJPQYOSZFRKLEUTAC","LURXHFECKZSYPTQGAOJVI","TFUKZELVARQCXIYPJHGSO","FIPYTACSXZKLRGOHJVEQU","ZKJQOGHVURAISXFLPYECT","XKOJAHVQUCETFPRYZGLSI","TUKZAVIFXEGQCSOLJRPHY","OSIPCFVRLAYKEHZTJGUQX","OYAQTCEKLGPRZVISUXFHJ","SKHCXEZLTFVQOIUPRAJGY","CRZPAEILFTOKUJVGXHQYS","OQVLPEYZFIGJRKUSXAHTC","VQTXURZKAPGHEIFCOLSJY","YVRZKXSOAEIPUQJHGCFLT","YEJTGFQPOZLCARSUIKVHX","XKASIECRHVQFPULZTOGJY","KAQVYSZLTFXCGEJIRUHOP","IYJXCUTOAPQKHEZFGRVSL","OIEPRLZGUVQHSYJAFTXCK","CIGVAZLKORXQYPHTEUSFJ","UVTCJFQOGXIZHLKYRASEP","FCVOYSJHZLKATXRIUPQGE","TJLQFSRKIUGPCVZHOEAXY","FUHLSRGTCOXAEZVQIYKPJ","CAGRHEUQZISYKXLFVPJOT","LASKUHEPJQXRCTZOVIYFG","IGKJSYLVFCUXETRAHZQPO","UZGXPIAFVOSLKRYQJTCHE","VKELXAFPOGSRIZCUQYTHJ","GCTJEUFRVLKAIOYSHZXQP","PHUOAXLYFTCRSEQIKGJZV","XLQYSIJHTREFPOKCUGVAZ","LUZXHQKIATOCGJYPFSVRE","XILVQZAFUKECYJGTPHSOR","GCQFHJKTAERVPIYUSZOLX","ZPRILGHYXTFVSQCAUKEOJ","SLFTYQPZKUAIVGRHEOCXJ","FCUVEOKHGZQSYJRXPAILT","AKZJRQCPVHYGSXLFITUOE","OKVEHCXPYRUGIAZJQFSLT","YZVHPIGSLREJQCXOKFATU","QTCILUZFVYHSAPGJEKXRO","YXKJOPHIVGARUTZEFLSCQ","OZPXURLHEKFQTSIVJYGCA","YIVEGRJLTPOAZFCQSUXHK","VPQUXLYGACSITFKEJHORZ","AOEQLYPFZUXCKHSTVIJRG","IFYTULEXKZRCOHASQPJGV","TASULVYKZPOCGIHJERXFQ","RGXYZCHVEAPTJISQUFKOL","XKVRTHJSLOZPIAYUEQGFC","EYIRXQTCUPHSVJFZLAKOG","ZRJSTQIGPELKUCHAOYVFX","EIXJPTZGRKVYCUFAOHQLS","LRSGUJZYXCIVQOAHTFPEK","ZHLOESVGIARXCUQYKPFJT","ZKQLVGOIFASTPUHYJRCXE","ZLPJQYTXEGAFHOSRCIUVK","ZVHYQJXCGTAFKLEISOPUR","KZGLYEQAURFHSXIVPTJCO","TIXPAYEKJLVGCQRUHOSZF","ESORYCVXLPKZFQJAUGIHT","FAJTCHORZGLIKXYSVUPQE","AOXHJEZFYLIQCPRVTSGKU","IZVAPOTEHCJQLKRGFUSXY","RTVYZHSIPGCEKJQUAXFOL","GSHOKEXAZCIQYTRJFVLPU","SXZLKIUGEVCPFHTQJARYO","QPCOTHISGLKYJFUAZXVRE","XPUEYATJHCOLVGSQRIZKF","GIKSZFHEQLTCVXJAYOPUR","RFSOEJPUAGKYHZIQCTLXV","UFHXJLITQPEGCKOSZYRAV","ZVQAFGXEIRSTPJYLHCOKU","ZITVJLSOAUGPCFYXHRQKE","RCZOIPEXFJAQGSYVLKHUT","TUHVJROCXIGEPLQAZYKSF","ATQJGKUIPLZXEYCRSOVFH","TVHYLSRAKIXJFGEPOZUCQ","CAPHZLGXQSIRTJYFOKEVU","FAYOKHEUZIRJXQTVGCSPL","IJCRUHVAPFYKGXLTSOQEZ","ZKIJLQEAUVHFTYRXCSGOP","ALFTJSRXUQPIOVZCYHEKG","ZASIVJQYUCRPEKGLTXFHO","OICQXZPEFUSTVALKGYRJH","ZOKVPHUXGRQIJCSEYALFT","FKACPHOSIREGUTYLJXZVQ","IZXOREFGSLPKUHAYCVTJQ","UVXZTCFAQEYLORSKHPJIG","PKVQCYSTLHRZIFAUEXJGO","IRFZSKGEHQVOLXCTJUPAY","XYHPVOTILEAUZJGSKQCRF","ERXJLFZQIGHPCSTYKUVOA","SZTIFCGVEKUJYPAOQXHRL","JPTGQOEYFIKURCVHXALZS","URJGTXZKICAOQSLVEYHFP","ZERGKOLTSUIXJFACVQHPY","GQCVAJYIKRZLTPSFHOUEX","OKRCTSGLZXQJEHPFVYUIA","GUKXARTQFYSCVEZIOJHLP","UTCIRLFHGJOSYZVPQKEAX","JPIOVSFZHUTQKCERXAGLY","LKJEGOHRTYQFXUSCVIPZA","LSETPUAHZYOICVRGJFXKQ","OPGHRVUXQEYLZFISTJKCA","VOKCSGFTXZEIRYALHJPQU","POTXFYCQIVZHLGJERAUSK","FAUIECXOYPLRHJKTSZQVG","XFAETYRCJUGVPQZOKSLHI","LGCVYIAZRFJSHQXTKUOPE","YKATQFIURCHPLSVGJEXOZ","IRUHTAXVYZKFPSEOJCLGQ","TAVEXIHLPOGSZRCJFQKUY","GFACLJSETKIXRZUYHVPOQ","XTJKSAZIQYRCLPGOHUFEV","GSFTZLJCVKRYUOXAQIEPH","GIOLPRXHCSUFKAVTJZEQY","SFCRPVGYKOUZJALQEXHIT","EUTOKQGFCLRAVZPJYSXHI","UOYSHGLTPZXRICFJEKAVQ","OTZIGVXSQHCPRYUKELAJF","SGZOEHLKYUPXCJRFTAVQI","JOCVZLGSUIAHPFKYTQERX","ZFSRJULQGKIOXEPYHTACV","FGSJCIYXHEAZTOLUKRVQP","YXHICZVFTSQJKLPOURGAE","XALRUOHJZYVEGQPKCSFIT","KCIJLRXYHAESGFQUOPVZT","AUTSXLECOGPZIHRVYQKFJ","GIZRAKEVOXLTCJSUHQPFY","ZKUPCORTFYEIAGJQXVLHS","JALHXZQIYSUROPCEGKVFT","KUIGTSQAJEOZYPCFHLXRV","LXICRFZJEUVYASPKQHTOG","EFUPZKRXLCAVJGQITHOSY","EUYGQKARZJVHLIPFCOSTX","AOXTKHRYLJZQEUCSPGVIF","SHUTLZEGRJYPCVAFXQOKI","GUZTAXQLKIRFYEOHJSPVC","RGOZPAXLYVJSHFICKTQUE","ASCHFQVTRLEKYUZIXGJPO","CQFRUSIXLOZPVJTGYAHEK","VGYURSHEXIKCFOAPTQLJZ","VFQCGPEAYISTXKORLUJHZ","UZJOYGVRETFSPLQAIKHCX","JKQRZFXICESTHPGOUYVAL","XGFYRJKCVTESZPHLQUIOA","YEPGFRALQOKJTXSZCIUVH","CXHPFAYKVZQORLJUTEGSI","PXHACSGJUILTYVQRFKEOZ","RSILHFAYCQJKVUGZTPXOE","IKAEOXFVPHSLRCQGZYJTU","GVKRJFLXZUOSAEIYPTCQH","TEXZOUVPICHGFLRYSQKAJ","JCEHLTRZQVFOPUSIKGYXA","GFLJHYXEAQTOPSKIUZVRC","ZGKJFVEAUHIXRTCLSPYQO","GXOTELHIQKUAFSVRPZYCJ","XRZEUGOIVAKSYPHJQCFLT","PYQVXGHSAKLRFTEZOUICJ","QGHOCVKFEPUTSRAIJYZLX","YRQVOLKJGFIXHEPCTUAZS","CTXYFQVZASEHPIOUJGRLK","GIZHRVQLJEYAKTSUCOPXF","XIGKSCLTRYJHZFUOQAPVE","RYCXPSEGIFAULKZTQJVHO","PXEQTGYSHICLAVRUZKJOF","AERXGTIHLUZSFKQYVPCJO","SKTPVFXILUZHYCEJAQROG","OCQUZKSJYLIVARFEHTPGX","ISZXFQUKHJOTCREPGYALV","LOSTQCIRZFVGYKPEAJHUX","QPFTRGUKOIVXESYCJZLAH","PXSUEIVOHZCKJFQLTGRAY","QYLRCVJOPEXGUTZKSAIFH","RJQPOFKXIHUZYVETCSLAG","HTFJEAISYQZUXLCGVPORK","ECGFLAHQJPORITXYUKVZS","FJGAIOSPTVXUZYHLQKERC","GEQLKYPICTUAFRSOVXZHJ","CGJHEZKSTIUQOFVRYXLAP","XYJSGTIKOVUFERLHCPAQZ","LQFVECITUGXHOYJKASRZP","HYGJQFUPZVORSKICLETXA","ACTXZRUYPOJLIEFSKQVGH","PHOLYCFUKRASEGTVQZXIJ","RTUOEZHPSKAFXLQYICVGJ","RAPTGQIJOSEFZUKVXCLHY","EUAKTQLJFOHCPSYVGRZXI","TYUPHSXVEZKIFQACRLJGO","ZHOEAIULSVJQKGRYFTXPC","CPEUIGVRFSOZAKYHQLTJX","ZCOEYRHVQFLSJIXUATGKP","FGSCJZKUTRVOLEYHQIPAX","SPKIGAUVQJXZYEHROCFTL","ITQVPZLEOGJUHKXRYFASC","GSAFTOHJQCYLUVPZEXRKI","ZPFKXLUJSRCAHOGYTVIEQ","QIFYPTAJELCSOXUKRZGVH","JFGZCQAELXKOIUHYRSTVP","TIGPACUOYZJHXKSVQEFRL","EATKLFGOCZVQHXRYSJIPU","SPOJYHVQXGZELUACKFITR","YTVIQXEZUJRFGCOLKSAPH","SPGHEQZJVXKIOAYLRUCFT","RFXCSUZIJAQTELHKVPOGY","PHXJESZRGFLKOAVIQUTYC","GUYCOKILATEJZXHFPRSVQ","GQTUFLAKCPVRYIOHXEZJS","AYVCGFTIQKLZSXEPHRJUO","EAXRUTPZVHCGLISYQFKOJ","SUVFHQGRLXEZAYJTCIPKO","PXKTOGRLHQAJFZCIYUSVE","ZGXYPLOSRCTAVFEUIQKHJ","OKEHXFQSIZGCRJLPATYUV","YXQILGVKPJOUTAZRCSEHF","TYQAGXSCZVKLJEOIHPURF","ELAJZPXRIFQVSGKTOCUHY","YIPXUJHGACTVQEKSOZRLF","ZPAGUYLVSRCIKOJXFTEQH","LYKIJURAEGVZSFPXHCOTQ","EULYFIOJTGXZQCPARHKSV"]

// "ZGXOEYTSRLIAPFUCQJVKH"
console.log('rankTeams',rankTeams(votes));